/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-09-13 13:12:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.space;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class spaceDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1598936639562L));
    _jspx_dependants.put("jar:file:/C:/workspaces/spring_workspace/SpaceUs/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspaces/spring_workspace/SpaceUs/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspaces/spring_workspace/SpaceUs/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 한글 인코딩처리 -->\r\n");
      if (_jspx_meth_fmt_005frequestEncoding_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"ftco-section ftco-property-details\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("      \t<div class=\"row justify-content-center\">\r\n");
      out.write("      \t\t<div class=\"col-md-12\">\r\n");
      out.write("      \t\t\t<div class=\"property-details\">\r\n");
      out.write("      \t\t\t\t<div class=\"img\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/work-1.jpg);\"></div>\r\n");
      out.write("      \t\t\t\t<div class=\"text text-center\">\r\n");
      out.write("      \t\t\t\t\t<span class=\"subheading\">Oakland</span>\r\n");
      out.write("      \t\t\t\t\t<h2>The Blue Sky Home</h2>\r\n");
      out.write("      \t\t\t\t</div>\r\n");
      out.write("      \t\t\t</div>\r\n");
      out.write("      \t\t</div>\r\n");
      out.write("      \t</div>\r\n");
      out.write("      \t<div class=\"row\">\r\n");
      out.write("      \t\t<div class=\"col-md-12 pills\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bd-example bd-example-tabs\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t  <ul class=\"nav nav-pills mb-3\" id=\"pills-tab\" role=\"tablist\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t    <li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t      <a class=\"nav-link active\" id=\"pills-description-tab\" data-toggle=\"pill\" href=\"#pills-description\" role=\"tab\" aria-controls=\"pills-description\" aria-expanded=\"true\">Features</a>\r\n");
      out.write("\t\t\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t\t\t    <li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t      <a class=\"nav-link\" id=\"pills-manufacturer-tab\" data-toggle=\"pill\" href=\"#pills-manufacturer\" role=\"tab\" aria-controls=\"pills-manufacturer\" aria-expanded=\"true\">Description</a>\r\n");
      out.write("\t\t\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t\t\t    <li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t      <a class=\"nav-link\" id=\"pills-review-tab\" data-toggle=\"pill\" href=\"#pills-review\" role=\"tab\" aria-controls=\"pills-review\" aria-expanded=\"true\">Review</a>\r\n");
      out.write("\t\t\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"tab-content\" id=\"pills-tabContent\">\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"tab-pane fade show active\" id=\"pills-description\" role=\"tabpanel\" aria-labelledby=\"pills-description-tab\">\r\n");
      out.write("\t\t\t\t\t\t    \t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t<ul class=\"features\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t<li class=\"check\"><span class=\"ion-ios-checkmark\"></span>Lot Area: 1,250 SQ FT</li>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t<li class=\"check\"><span class=\"ion-ios-checkmark\"></span>Bed Rooms: 4</li>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t<li class=\"check\"><span class=\"ion-ios-checkmark\"></span>Bath Rooms: 4</li>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t<li class=\"check\"><span class=\"ion-ios-checkmark\"></span>Luggage</li>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t<li class=\"check\"><span class=\"ion-ios-checkmark\"></span>Garage: 2</li>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t    \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t    \t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t<ul class=\"features\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t<li class=\"check\"><span class=\"ion-ios-checkmark\"></span>Floor Area: 1,300 SQ FT</li>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t<li class=\"check\"><span class=\"ion-ios-checkmark\"></span>Year Build:: 2019</li>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t<li class=\"check\"><span class=\"ion-ios-checkmark\"></span>Water</li>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t<li class=\"check\"><span class=\"ion-ios-checkmark\"></span>Stories: 2</li>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t<li class=\"check\"><span class=\"ion-ios-checkmark\"></span>Roofing: New</li>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t    \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t    \t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t<ul class=\"features\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t<li class=\"check\"><span class=\"ion-ios-checkmark\"></span>Floor Area: 1,300 SQ FT</li>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t<li class=\"check\"><span class=\"ion-ios-checkmark\"></span>Year Build:: 2019</li>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t<li class=\"check\"><span class=\"ion-ios-checkmark\"></span>Water</li>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t<li class=\"check\"><span class=\"ion-ios-checkmark\"></span>Stories: 2</li>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t<li class=\"check\"><span class=\"ion-ios-checkmark\"></span>Roofing: New</li>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t    \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"tab-pane fade\" id=\"pills-manufacturer\" role=\"tabpanel\" aria-labelledby=\"pills-manufacturer-tab\">\r\n");
      out.write("\t\t\t\t\t\t      <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then she continued her way.</p>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"tab-pane fade\" id=\"pills-review\" role=\"tabpanel\" aria-labelledby=\"pills-review-tab\">\r\n");
      out.write("\t\t\t\t\t\t      <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t<h3 class=\"head\">23 Reviews</h3>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t<div class=\"review d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t<div class=\"user-img\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/person_1.jpg)\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t<span class=\"text-left\">Jacob Webb</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t<span class=\"text-right\">14 March 2018</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t<p class=\"star\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t\t\t<span class=\"text-right\"><a href=\"#\" class=\"reply\"><i class=\"icon-reply\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrov</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t<div class=\"review d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t<div class=\"user-img\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/person_2.jpg)\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t<span class=\"text-left\">Jacob Webb</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t<span class=\"text-right\">14 March 2018</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t<p class=\"star\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t\t\t<span class=\"text-right\"><a href=\"#\" class=\"reply\"><i class=\"icon-reply\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrov</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t<div class=\"review d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t<div class=\"user-img\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/person_3.jpg)\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t<span class=\"text-left\">Jacob Webb</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t<span class=\"text-right\">14 March 2018</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t<p class=\"star\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t\t\t<span class=\"text-right\"><a href=\"#\" class=\"reply\"><i class=\"icon-reply\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrov</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t<div class=\"rating-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t<h3 class=\"head\">Give a Review</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t<div class=\"wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t<p class=\"star\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t(98%)\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t\t\t<span>20 Reviews</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t<p class=\"star\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t(85%)\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t\t\t<span>10 Reviews</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t<p class=\"star\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t(70%)\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t\t\t<span>5 Reviews</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t<p class=\"star\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t(10%)\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t\t\t<span>0 Reviews</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t<p class=\"star\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t<i class=\"ion-ios-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t\t\t(0%)\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t\t\t\t<span>0 Reviews</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t   \t</div>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("<!-- 컨텐츠 끝 -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005frequestEncoding_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:requestEncoding
    org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag _jspx_th_fmt_005frequestEncoding_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag) _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag.class);
    boolean _jspx_th_fmt_005frequestEncoding_005f0_reused = false;
    try {
      _jspx_th_fmt_005frequestEncoding_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005frequestEncoding_005f0.setParent(null);
      // /WEB-INF/views/space/spaceDetail.jsp(7,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005frequestEncoding_005f0.setValue("utf-8");
      int _jspx_eval_fmt_005frequestEncoding_005f0 = _jspx_th_fmt_005frequestEncoding_005f0.doStartTag();
      if (_jspx_th_fmt_005frequestEncoding_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005frequestEncoding_005f0);
      _jspx_th_fmt_005frequestEncoding_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005frequestEncoding_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005frequestEncoding_005f0_reused);
    }
    return false;
  }
}
