/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-09-13 13:15:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.space;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class space_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1598936639562L));
    _jspx_dependants.put("jar:file:/C:/workspaces/spring_workspace/SpaceUs/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspaces/spring_workspace/SpaceUs/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspaces/spring_workspace/SpaceUs/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 한글 인코딩처리 -->\r\n");
      if (_jspx_meth_fmt_005frequestEncoding_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 컨텐츠 시작 -->\r\n");
      out.write("    <div class=\"hero-wrap ftco-degree-bg\"\r\n");
      out.write("    \t style=\"background-image: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/bg_1.jpg');\r\n");
      out.write("    \t \t\theight: 400px\"\r\n");
      out.write("    \t data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("      <div class=\"overlay\"></div>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row no-gutters slider-text justify-content-center align-items-center\">\r\n");
      out.write("          <div class=\"col-lg-8 col-md-6 ftco-animate d-flex align-items-end\">\r\n");
      out.write("          \t<div class=\"text text-center mx-auto\" style=\"margin-bottom:50%;\">\r\n");
      out.write("\t            <h1 class=\"mb-4\">공간 등록하기</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Breadcrumb Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Property Submit Section Begin -->\r\n");
      out.write("    <section class=\"property-submit-section spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"property-submit-form\">\r\n");
      out.write("                        <form action=\"#\">\r\n");
      out.write("                            <div class=\"pf-title\">\r\n");
      out.write("                                <h4>Title</h4>\r\n");
      out.write("                                <input type=\"text\" placeholder=\"Your Title*\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pf-summernote\">\r\n");
      out.write("                                <h4>Content</h4>\r\n");
      out.write("                                <textarea class=\"texteditor-content\" name=\"example\"></textarea>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pf-location\">\r\n");
      out.write("                                <h4>Property Location</h4>\r\n");
      out.write("                                <div class=\"location-inputs\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"Address\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"Neighborhood\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"City\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"State\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"Country\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"Posta Code / Zip\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pf-map\">\r\n");
      out.write("                                <h4>Goolge Map</h4>\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-lg-4\">\r\n");
      out.write("                                        <div class=\"map-inputs\">\r\n");
      out.write("                                            <input type=\"text\" placeholder=\"Latitude\">\r\n");
      out.write("                                            <input type=\"text\" placeholder=\"Longitude\">\r\n");
      out.write("                                            <input type=\"text\" placeholder=\"Street View\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <button type=\"button\" class=\"site-btn\">PPlace the pin the address above</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                        <div class=\"g-map\">\r\n");
      out.write("                                            <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d735515.5813275519!2d-80.41163541934742!3d43.93644386501528!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x882a55bbf3de23d7%3A0x3ada5af229b47375!2sMono%2C%20ON%2C%20Canada!5e0!3m2!1sen!2sbd!4v1583262687289!5m2!1sen!2sbd\" height=\"245\" style=\"border:0;\" allowfullscreen=\"\"></iframe>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pf-type\">\r\n");
      out.write("                                <h4>Property type</h4>\r\n");
      out.write("                                <div class=\"type-item\">\r\n");
      out.write("                                    <label for=\"pt-apart\">Apartment\r\n");
      out.write("                                        <input type=\"checkbox\" id=\"pt-apart\">\r\n");
      out.write("                                        <span class=\"checkbox\"></span>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <label for=\"pt-house\">House\r\n");
      out.write("                                        <input type=\"checkbox\" id=\"pt-house\">\r\n");
      out.write("                                        <span class=\"checkbox\"></span>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <label for=\"pt-off\">Office\r\n");
      out.write("                                        <input type=\"checkbox\" id=\"pt-off\">\r\n");
      out.write("                                        <span class=\"checkbox\"></span>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <label for=\"pt-villa\">Villa\r\n");
      out.write("                                        <input type=\"checkbox\" id=\"pt-villa\">\r\n");
      out.write("                                        <span class=\"checkbox\"></span>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <label for=\"pt-store\">Store\r\n");
      out.write("                                        <input type=\"checkbox\" id=\"pt-store\">\r\n");
      out.write("                                        <span class=\"checkbox\"></span>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <label for=\"pt-rest\">Resturent\r\n");
      out.write("                                        <input type=\"checkbox\" id=\"pt-rest\">\r\n");
      out.write("                                        <span class=\"checkbox\"></span>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pf-status\">\r\n");
      out.write("                                <h4>Property status</h4>\r\n");
      out.write("                                <div class=\"status-item\">\r\n");
      out.write("                                    <label for=\"ps-rent\">For rent\r\n");
      out.write("                                        <input type=\"checkbox\" id=\"ps-rent\">\r\n");
      out.write("                                        <span class=\"checkbox\"></span>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <label for=\"ps-sale\">For sale\r\n");
      out.write("                                        <input type=\"checkbox\" id=\"ps-sale\">\r\n");
      out.write("                                        <span class=\"checkbox\"></span>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pf-feature-price\">\r\n");
      out.write("                                <h4>Featured Price</h4>\r\n");
      out.write("                                <div class=\"fp-inputs\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"Price\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"Second Price ( Optional )\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"After Price Label (ex: monthly)\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pf-feature\">\r\n");
      out.write("                                <h4>Property Features</h4>\r\n");
      out.write("                                <div class=\"features-list\">\r\n");
      out.write("                                    <div class=\"feature-item\">\r\n");
      out.write("                                        <label for=\"air\">Air conditioning\r\n");
      out.write("                                            <input type=\"checkbox\" id=\"air\">\r\n");
      out.write("                                            <span class=\"checkbox\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <label for=\"lundry\">Laundry\r\n");
      out.write("                                            <input type=\"checkbox\" id=\"lundry\">\r\n");
      out.write("                                            <span class=\"checkbox\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <label for=\"refrigerator\">Refrigerator\r\n");
      out.write("                                            <input type=\"checkbox\" id=\"refrigerator\">\r\n");
      out.write("                                            <span class=\"checkbox\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <label for=\"washer\">Washer\r\n");
      out.write("                                            <input type=\"checkbox\" id=\"washer\">\r\n");
      out.write("                                            <span class=\"checkbox\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"feature-item\">\r\n");
      out.write("                                        <label for=\"barbeque\">Barbeque\r\n");
      out.write("                                            <input type=\"checkbox\" id=\"barbeque\">\r\n");
      out.write("                                            <span class=\"checkbox\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <label for=\"lawn\">Lawn\r\n");
      out.write("                                            <input type=\"checkbox\" id=\"lawn\">\r\n");
      out.write("                                            <span class=\"checkbox\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <label for=\"sauna\">Sauna\r\n");
      out.write("                                            <input type=\"checkbox\" id=\"sauna\">\r\n");
      out.write("                                            <span class=\"checkbox\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <label for=\"wifi\">Wifi\r\n");
      out.write("                                            <input type=\"checkbox\" id=\"wifi\">\r\n");
      out.write("                                            <span class=\"checkbox\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"feature-item\">\r\n");
      out.write("                                        <label for=\"dryer\">Dryer\r\n");
      out.write("                                            <input type=\"checkbox\" id=\"dryer\">\r\n");
      out.write("                                            <span class=\"checkbox\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <label for=\"microwave\">Microwave\r\n");
      out.write("                                            <input type=\"checkbox\" id=\"microwave\">\r\n");
      out.write("                                            <span class=\"checkbox\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <label for=\"pool\">Swimming Pool\r\n");
      out.write("                                            <input type=\"checkbox\" id=\"pool\">\r\n");
      out.write("                                            <span class=\"checkbox\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <label for=\"window\">Window Coverings\r\n");
      out.write("                                            <input type=\"checkbox\" id=\"window\">\r\n");
      out.write("                                            <span class=\"checkbox\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"feature-item\">\r\n");
      out.write("                                        <label for=\"gym\">Gym\r\n");
      out.write("                                            <input type=\"checkbox\" id=\"gym\">\r\n");
      out.write("                                            <span class=\"checkbox\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <label for=\"shower\">OutdoorShower\r\n");
      out.write("                                            <input type=\"checkbox\" id=\"shower\">\r\n");
      out.write("                                            <span class=\"checkbox\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <label for=\"tv\">Tv Cable\r\n");
      out.write("                                            <input type=\"checkbox\" id=\"tv\">\r\n");
      out.write("                                            <span class=\"checkbox\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <label for=\"villa\">Villa\r\n");
      out.write("                                            <input type=\"checkbox\" id=\"villa\">\r\n");
      out.write("                                            <span class=\"checkbox\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pf-feature-image\">\r\n");
      out.write("                                <h4>Featured Image</h4>\r\n");
      out.write("                                <div class=\"feature-image-content\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pf-property-details\">\r\n");
      out.write("                                <h4>Property details</h4>\r\n");
      out.write("                                <div class=\"property-details-inputs\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"Property ID\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"Area Size ( Only digits )\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"Size Prefix\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"Bedrooms\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"Bathrooms\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"Garages\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"Garages Size\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"Year Built\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"Virtual Tour Video URL\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button type=\"submit\" class=\"site-btn\">Submit Property</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Property Submit Section End -->\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<!-- 컨텐츠 끝 -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005frequestEncoding_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:requestEncoding
    org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag _jspx_th_fmt_005frequestEncoding_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag) _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag.class);
    boolean _jspx_th_fmt_005frequestEncoding_005f0_reused = false;
    try {
      _jspx_th_fmt_005frequestEncoding_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005frequestEncoding_005f0.setParent(null);
      // /WEB-INF/views/space/space.jsp(7,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005frequestEncoding_005f0.setValue("utf-8");
      int _jspx_eval_fmt_005frequestEncoding_005f0 = _jspx_th_fmt_005frequestEncoding_005f0.doStartTag();
      if (_jspx_th_fmt_005frequestEncoding_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005frequestEncoding_005f0);
      _jspx_th_fmt_005frequestEncoding_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005frequestEncoding_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005frequestEncoding_005f0_reused);
    }
    return false;
  }
}
